### ISSUE TITLE
Some difficulties, please comment

### ISSUE THREAD

**Issue by ConfidantCommunications** [photodude/FOF3-Basic#4]
Hi Walt,
I attempted to follow the instructions. I created my own installation xml manifest and installed the base files successfully. I renamed the sql tables to match what I wanted for my project.

First off, when I visited the admin page for the component I noticed that there was no categories view. The column on the left only said "Plans" (my replacement for your "Examples"). I tried manually adding a row to the Categories table in the database and that allowed me to create a Plan entry via Joomla. Prior to that, I couldn't because there were no Categories to associate with the Plan.

I was finally able to make "Categories" appear on the left by changing the view in the URL like so: /administrator/index.php?option=com_componentname&view=Categories

The scaffolding is working in that it created View files for Categories and Plans. However, there are still no language files created. What did I miss?
Thanks!
-Allan

**Comment by photodude** [comment]
If you want to upload the files, I'll try to take a look.

Off hand I've found that in some cases the formatting of the MySQL files can cause issues with Joomla installing things correctly (default values missing, etc). In the installation xml manifest Did you specify the SQL file driver as `mysqli`? That was something that caused me some issues at one point.

As for the language files not being created from the scaffolding, can you replicate the creation failure with the FOF3-basic files? If you can, there might be a bug in FOF3 that would need to be addressed with Akeeba.

**Comment by ConfidantCommunications** [comment]
Okay, I installed just the basic tutorial files with no modifications. I forgot that the language files would get created in the components/language folder, so that is in fact working in both cases—my apologies.

However, it still has the same behaviour with Categories—it doesn't show in the left column until I modify the URL.
Thanks!

**Comment by photodude** [comment]
I can confirm that I get the same issue Categories with the step 1 files and FOF 3.0.14. I'll see if I can determine if it's an issue with the tutorial or with FOF3. I originally created this tutorial with FOF 3.0.3 and FOF 3.0.5 on Joomla 3.5.0 I don't remember this being an issue.

**Comment by poproar** [comment]
i just started this tutorial and I also had this issue. I think Categories showed up for the very first load but as i stepped in to the new example form and came out it was gone. i had not turned off the scaffolding at this point either. This is using FOF 3.0.14 on J! 3.6.2 in a joomlatools vagrant box where all files and directories are writeable.

**Comment by photodude** [comment]
I'm beginning to think there is an issue in FOF3 or in Joomla 3.6.2 since this is definitely not the behavior I saw when I set up the tutorial using FOF 3.0.3 on Joomla 3.5.1. I'm going to see if I can reproduce using the original set up.

**Comment by photodude** [comment]
I have attempted to recreate with the initial setup using FOF 3.0.3 on Joomla 3.5.1 and was able to reproduce the issue. 

At this point, I assume only the default view shows up after the component is initially installed. 

We'll need to adjust the Step 2 instructions to indicate how to get to additional views via the URL based on your component's table.

**Comment by poproar** [comment]
There is this note https://groups.google.com/d/msg/frameworkonframework/CmrP20vnwoU/CUsW8kIXBQAJ

**Comment by photodude** [comment]
I've added the following note to the tutorial instructions. Thanks for your feedback.

**Note 3:** Browsing the views with or without a basic menu requires remembering what list views you are expecting based on your tables. For this example we are expecting two list views, Examples and Catagories. Each of these need to be browsed, to the have the Scaffolding create the assoceated files. The expected url for these list views are [yoursite url or local url]/administrator/index.php?option=com_[your component's name i.e. fof3basic]&view=[table view name] For example the fof3basic_categories table has the table view name Categories and the fof3basic_examples table has the table view name Examples. This table view name concept is especially importaint to remember for the frontend views
